<?php
/**
 * TL_ROOT/system/modules/banner/languages/sv/default.php 
 * 
 * TYPOlight extension: banner 1.10.0 stable 
 * Swedish translation file 
 * 
 * Copyright : &copy; 2007..2010 Glen Langer 
 * License   : GNU GPL V2 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Matz Särås (SuperMatz), http://www.xprofil.se 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['id'] = "ID";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['picture'] = "Banner";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['name'] = "Namn";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['URL'] = "Mål-URL";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['views'] = "Visningar";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['clicks'] = "Klick";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['NoURL'] = "Ingen URL";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['Prio'] = "Prioritet";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['active'] = "Aktiv";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['pub_yes'] = "ja";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['pub_no'] = "nej";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['max_yes'] = "(Maximum)";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['modname'] = "Banner-modul";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['export'] = "Exportera";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['export_button_title'] = "Knappen öppnar ett nytt fönster.";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['export_headline'] = "Kategori,ID,Namn,URL,Bild,Prioritet,Visa från,Visa till,Publicerad,Visningar,Klick";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['zero_text'] = "Statistikräknaren för bannern återställs till noll.";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['zero_confirm'] = "Vill du verkligen återställa banner-statistiken (visningar och klick)?";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['kat'] = "Kategori";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['allkat'] = "Alla kategorier";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['read_error'] = "Banner-filen kunde inte hittas eller läsfel!";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['select'] = "Vänligen välj";
 
?>
