<?php
/**
 * TL_ROOT/system/modules/banner/languages/sv/modules.php 
 * 
 * TYPOlight extension: banner 1.10.0 stable 
 * Swedish translation file 
 * 
 * Copyright : &copy; 2007..2010 Glen Langer 
 * License   : GNU GPL V2 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Matz Särås (SuperMatz), http://www.xprofil.se 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['banner']['0'] = "Banner";
$GLOBALS['TL_LANG']['MOD']['banner']['1'] = "En liten banner-annonseringsmodul";
$GLOBALS['TL_LANG']['MOD']['bannerstat']['0'] = "Banner-statistik";
$GLOBALS['TL_LANG']['MOD']['bannerstat']['1'] = "Banner-statistik från banner-modul.";
$GLOBALS['TL_LANG']['FMD']['banner']['0'] = "Banner";
$GLOBALS['TL_LANG']['FMD']['banner']['1'] = "Visa en banner";
 
?>
