<?php
/**
 * TL_ROOT/system/modules/banner/languages/sv/tl_module.php 
 * 
 * TYPOlight extension: banner 1.10.0 stable 
 * Swedish translation file 
 * 
 * Copyright : &copy; 2007..2010 Glen Langer 
 * License   : GNU GPL V2 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Matz Särås (SuperMatz), http://www.xprofil.se 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['banner_hideempty']['0'] = "Göm om tom";
$GLOBALS['TL_LANG']['tl_module']['banner_hideempty']['1'] = "Göm modulen (frontend) om inga aktiva banners finns.";
$GLOBALS['TL_LANG']['tl_module']['banner_categories']['0'] = "Banner-kategorier";
$GLOBALS['TL_LANG']['tl_module']['banner_categories']['1'] = "Välj de banner-kategorier som ska inkluderas.";
$GLOBALS['TL_LANG']['tl_module']['banner_template']['0'] = "Banner-mall";
$GLOBALS['TL_LANG']['tl_module']['banner_template']['1'] = "Välj en banner-mall. Banner-mallarnas filer börjar med <em>mod_banner_list_</em>.";
$GLOBALS['TL_LANG']['tl_module']['banner_useragent']['0'] = "Ingen registering av denna HTTP_USER_AGENT-identifierare";
$GLOBALS['TL_LANG']['tl_module']['banner_useragent']['1'] = "Här kan du specificera en HTTP_USER_AGENT-identifierare som gör att dina åtgärder inte räknas. HTTP_USER_AGENT-identifierare måste ändras i din webbläsare.<br />Se Wikin.";
 
?>
