<?php
/**
 * TL_ROOT/system/modules/banner/languages/it/default.php 
 * 
 * TYPOlight extension: banner 1.10.0 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2007..2010 Glen Langer 
 * License   : GNU GPL V2 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Paolo Brunelli (PaoloB), http://www.typolightcms.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['id'] = "ID";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['picture'] = "Banner";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['name'] = "Nome";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['URL'] = "Target URL";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['views'] = "Visualizzazioni";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['clicks'] = "Click";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['NoURL'] = "Nessun URL";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['Prio'] = "Priorità";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['active'] = "Attivo";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['pub_yes'] = "si";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['pub_no'] = "no";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['max_yes'] = "(massimo)";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['modname'] = "Modulo Banner";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['export'] = "Esporta";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['export_button_title'] = "Cliccando il pulsante si aprirà una nuova finestra";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['export_headline'] = "Categoria,ID,Nome,URL,Immagine,Priorità,Visualizza dal,Visualizza fino a,Pubblicato,Visualizzazioni,Click";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['zero_text'] = "Il contatore delle statistiche del banner sarà azzerato";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['zero_confirm'] = "Vuoi realmente azzerare i contatori delle statistiche del banner (visualizzazioni e click)?";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['kat'] = "Categoria";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['allkat'] = "Tutte le categorie";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['read_error'] = "Il file del banner non trovato o errore nella lettura!";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['select'] = "Selezionare";
 
?>
