<?php
/**
 * TL_ROOT/system/modules/banner/languages/it/modules.php 
 * 
 * TYPOlight extension: banner 1.10.0 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2007..2010 Glen Langer 
 * License   : GNU GPL V2 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Paolo Brunelli (PaoloB), http://www.typolightcms.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['banner']['0'] = "Banner";
$GLOBALS['TL_LANG']['MOD']['banner']['1'] = "Modulo per la gestione di banner pubblicitari";
$GLOBALS['TL_LANG']['MOD']['bannerstat']['0'] = "Statistiche banner";
$GLOBALS['TL_LANG']['MOD']['bannerstat']['1'] = "Statistiche relative al modulo banner";
$GLOBALS['TL_LANG']['FMD']['banner']['0'] = "Banner";
$GLOBALS['TL_LANG']['FMD']['banner']['1'] = "Visualizza banner";
 
?>
