<?php
/**
 * TL_ROOT/system/modules/banner/languages/it/tl_banner_category.php 
 * 
 * TYPOlight extension: banner 1.10.0 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2007..2010 Glen Langer 
 * License   : GNU GPL V2 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Paolo Brunelli (PaoloB), http://www.typolightcms.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_banner_category']['title']['0'] = "Categoria";
$GLOBALS['TL_LANG']['tl_banner_category']['title']['1'] = "Indicare il nome della categoria";
$GLOBALS['TL_LANG']['tl_banner_category']['tstamp']['0'] = "Data revisione";
$GLOBALS['TL_LANG']['tl_banner_category']['tstamp']['1'] = "Data ultima modifica";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default']['0'] = "Immagine default banner";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default']['1'] = "Questo banner sarà mostrato in assenza di banner attivi. <br /> Questa selezione ha la priorità sulla definizione modulo \"Nascondi quando vuota\".";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default_name']['0'] = "Nome banner";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default_name']['1'] = "Il nome sarà utilizzato per il tag title";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default_image']['0'] = "Immagine di default banner";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default_image']['1'] = "Selezionare il banner. (GIF,JPG,PNG,SWF)";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default_url']['0'] = "URL destinazione banner";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default_url']['1'] = "Inserire l'URL di destinazione del banner";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default_target']['0'] = "Link interno";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default_target']['1'] = "Se viene selezionata questa opzione, la destinazione del banner sarà visualizzata all'interno dello stesso browser.";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_protected']['0'] = "Protezione accesso";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_protected']['1'] = "Visualizza i banner di questa categoria solo ai menbri di questi gruppi.";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_groups']['0'] = "Gruppi abilitati";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_groups']['1'] = "Selezionare i grippi alla quale abilitare la visualizzazione di questa categoria di banner.";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_numbers']['0'] = "Visualizza tutti i banner";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_numbers']['1'] = "Se questa opzione è selezionata, tutti i banner attivi verranno mostrati.";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_random']['0'] = "Ordine casuale";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_random']['1'] = "Selezionando questa opzione, i banner saranno mostrati in ordine casuale.";
$GLOBALS['TL_LANG']['tl_banner_category']['title_legend'] = "Categoria e template banner";
$GLOBALS['TL_LANG']['tl_banner_category']['default_legend'] = "Dettagli banner di default";
$GLOBALS['TL_LANG']['tl_banner_category']['protected_legend'] = "Protezione accesso";
$GLOBALS['TL_LANG']['tl_banner_category']['number_legend'] = "Numero di banner";
$GLOBALS['TL_LANG']['tl_banner_category']['deleteConfirm'] = "Eliminando la categoria verranno eliminati anche tutti i banner associati. Vuoi realmente liminare la categoria ID %s?";
$GLOBALS['TL_LANG']['tl_banner_category']['new']['0'] = "Nuova categoria";
$GLOBALS['TL_LANG']['tl_banner_category']['new']['1'] = "Crea una nuova categoria";
$GLOBALS['TL_LANG']['tl_banner_category']['edit']['0'] = "Modifica categoria";
$GLOBALS['TL_LANG']['tl_banner_category']['edit']['1'] = "Modifica categoria ID %s";
$GLOBALS['TL_LANG']['tl_banner_category']['copy']['0'] = "Copia categoria";
$GLOBALS['TL_LANG']['tl_banner_category']['copy']['1'] = "Copia categoria ID %s";
$GLOBALS['TL_LANG']['tl_banner_category']['delete']['0'] = "Elimina categoria";
$GLOBALS['TL_LANG']['tl_banner_category']['delete']['1'] = "Elimina categoria ID %s";
$GLOBALS['TL_LANG']['tl_banner_category']['show']['0'] = "Dettagli categoria";
$GLOBALS['TL_LANG']['tl_banner_category']['show']['1'] = "Mostra i dettagli della categoria ID %s";
$GLOBALS['TL_LANG']['tl_banner_category']['stat']['0'] = "Statistiche categoria";
$GLOBALS['TL_LANG']['tl_banner_category']['stat']['1'] = "Mostra i dettagli della categoria ID %s";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_protected_catagory'] = "Accesso categoria";
 
?>
