<?php
/**
 * TL_ROOT/system/modules/banner/languages/it/tl_module.php 
 * 
 * TYPOlight extension: banner 1.10.0 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2007..2010 Glen Langer 
 * License   : GNU GPL V2 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Paolo Brunelli (PaoloB), http://www.typolightcms.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['banner_hideempty']['0'] = "Nascondi se vuota";
$GLOBALS['TL_LANG']['tl_module']['banner_hideempty']['1'] = "Nascondi il modulo quando non vi sono banner attivi";
$GLOBALS['TL_LANG']['tl_module']['banner_categories']['0'] = "Categoria banner";
$GLOBALS['TL_LANG']['tl_module']['banner_categories']['1'] = "Selezionare la categoria banner che si vuole includere";
$GLOBALS['TL_LANG']['tl_module']['banner_template']['0'] = "Template banner";
$GLOBALS['TL_LANG']['tl_module']['banner_template']['1'] = "Selezionare il template del banner. I template iniziano con <em>mod_banner_list_</em>";
$GLOBALS['TL_LANG']['tl_module']['banner_useragent']['0'] = "Non conteggiare questo identificativo HTTP_USER_AGENT";
$GLOBALS['TL_LANG']['tl_module']['banner_useragent']['1'] = "Modificando nel proprio browser la stringa user agent è possibile evitare il conteggio da questo determinato computer. <br /> Istruzioni dettagliate, possono essere trovate nel Wiki.";
 
?>
