<?php
/**
 * TL_ROOT/system/modules/banner/languages/ru/default.php 
 * 
 * TYPOlight extension: banner 1.10.0 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; 2007..2010 Glen Langer 
 * License   : GNU GPL V2 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Dmitry Kuznetsov (kuzmich), http://on.freedom-vrn.ru 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['id'] = "ID";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['picture'] = "Изображение";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['name'] = "Имя";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['URL'] = "Целевой URL";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['views'] = "Просмотров";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['clicks'] = "Нажатий";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['NoURL'] = "Нет URL";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['Prio'] = "Приоритет";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['active'] = "Активность";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['pub_yes'] = "да";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['pub_no'] = "нет";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['max_yes'] = "(Максимум)";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['modname'] = "Модуль баннера";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['export'] = "Экспорт";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['export_button_title'] = "Кнопка открывает новое окно";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['export_headline'] = "Категория,ID,Имя,URL,Изображение,Приоритет,Показывать с,Показывать до,Опубликовано,Просмотров,Нажатий";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['zero_text'] = "Счетчик статистики баннера будет сброшен.";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['zero_confirm'] = "Вы действительно хотите сбросить счетчик статистики баннера (просмотры и нажатия)";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['kat'] = "Категория";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['allkat'] = "Все категории";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['read_error'] = "Не найден файл баннера или ошибка чтения!";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['select'] = "Пожалуйста, выберите";
 
?>
