<?php
/**
 * TL_ROOT/system/modules/banner/languages/ru/explain.php 
 * 
 * TYPOlight extension: banner 1.10.0 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; 2007..2010 Glen Langer 
 * License   : GNU GPL V2 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Dmitry Kuznetsov (kuzmich), http://on.freedom-vrn.ru 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['XPL']['banner_help']['0']['0'] = "Имя баннера";
$GLOBALS['TL_LANG']['XPL']['banner_help']['0']['1'] = "Отображается в названии баннера при наведении на него, а также в шаблоне под изображением банера.";
$GLOBALS['TL_LANG']['XPL']['banner_help']['1']['0'] = "URL баннера";
$GLOBALS['TL_LANG']['XPL']['banner_help']['1']['1'] = "Адрес назначения, по которой перейдет пользователь, нажавший на изображение баннера.<br />URL должен начинаться с http://, напр.:<br /><br /><pre> http://www.typolight.org </pre><br/>Не используя это поле, изображение банера будет вставлено без ссылки.";
$GLOBALS['TL_LANG']['XPL']['banner_help']['2']['0'] = "Вес баннера";
$GLOBALS['TL_LANG']['XPL']['banner_help']['2']['1'] = "Баннер с более высоким весом, будет показан чаще, чем баннер с более низким.<br />";
$GLOBALS['TL_LANG']['XPL']['banner_help']['3']['0'] = "Изображение баннера";
$GLOBALS['TL_LANG']['XPL']['banner_help']['3']['1'] = "Графический файл может быть выбран как банер из списка файлов, файловой системы.";
$GLOBALS['TL_LANG']['XPL']['banner_help']['4']['0'] = "Комментарий баннера";
$GLOBALS['TL_LANG']['XPL']['banner_help']['4']['1'] = "Комментарий используется для тега заголовка, в исходный код, и будет показан, при наведении мыши на изображение баннера.";
$GLOBALS['TL_LANG']['XPL']['banner_help']['5']['0'] = "Показывать с (Дата & Время)";
$GLOBALS['TL_LANG']['XPL']['banner_help']['5']['1'] = "Если вы введете здесь дату и время, то текущий баннер не будет показан на вебсайте раньше этого момента. Время также может быть внесено вручную. <br/>Пример:<br/><br/><pre> 24.12.2007 20:15 </pre><br />";
$GLOBALS['TL_LANG']['XPL']['banner_help']['6']['0'] = "Показывать до (Дата & Время)";
$GLOBALS['TL_LANG']['XPL']['banner_help']['6']['1'] = "Если вы введете здесь дату и время, то текущий баннер не будет показан на вебсайте позже этого момента. Время также может быть внесено вручную.<br/>Пример:<br/><br/><pre> 24.12.2007 23:59 </pre><br />";
$GLOBALS['TL_LANG']['XPL']['banner_help']['7']['0'] = "Ограничение числа просмотров";
$GLOBALS['TL_LANG']['XPL']['banner_help']['7']['1'] = "Если число введено, текущий баннер не будет отображаться после этого количества просмотров.<br />Опция \"Ограничение числа просмотров и кликов\" должна быть активирована.<br />Пример:<br /><br /><pre>  1000</pre><br />";
$GLOBALS['TL_LANG']['XPL']['banner_help']['8']['0'] = "Ограничение числа нажатий";
$GLOBALS['TL_LANG']['XPL']['banner_help']['8']['1'] = "Если число введено, текущий баннер не будет отображаться после этого количества нажатий.<br />Опция \"Ограничение числа просмотров и кликов\" должна быть активирована.<br />Пример:<br /><br /><pre>   100</pre><br />";
$GLOBALS['TL_LANG']['XPL']['banner_help']['9']['0'] = "Идентификатор HTTP_USER_AGENT";
$GLOBALS['TL_LANG']['XPL']['banner_help']['9']['1'] = "Подробные инструкции по данной опции можно найти в Wiki.";
 
?>