<?php
/**
 * TL_ROOT/system/modules/banner/languages/ru/modules.php 
 * 
 * TYPOlight extension: banner 1.10.0 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; 2007..2010 Glen Langer 
 * License   : GNU GPL V2 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Dmitry Kuznetsov (kuzmich), http://on.freedom-vrn.ru 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['banner']['0'] = "Баннер";
$GLOBALS['TL_LANG']['MOD']['banner']['1'] = "Маленький модуль баннерной рекламы";
$GLOBALS['TL_LANG']['MOD']['bannerstat']['0'] = "Статистика баннеров";
$GLOBALS['TL_LANG']['MOD']['bannerstat']['1'] = "Отображение статистики баннеров из модуля показа баннеров.";
$GLOBALS['TL_LANG']['FMD']['banner']['0'] = "Баннер";
$GLOBALS['TL_LANG']['FMD']['banner']['1'] = "Показать баннер";
 
?>
