<?php
/**
 * TL_ROOT/system/modules/banner/languages/ru/tl_banner.php 
 * 
 * TYPOlight extension: banner 1.10.0 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; 2007..2010 Glen Langer 
 * License   : GNU GPL V2 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Dmitry Kuznetsov (kuzmich), http://on.freedom-vrn.ru 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_banner']['banner_type']['0'] = "Источник баннера";
$GLOBALS['TL_LANG']['tl_banner']['banner_type']['1'] = "Выбор внутреннего или внешнего источника баннера.";
$GLOBALS['TL_LANG']['tl_banner']['banner_name']['0'] = "Имя баннера";
$GLOBALS['TL_LANG']['tl_banner']['banner_name']['1'] = "Пожалуйста, введите имя баннера.";
$GLOBALS['TL_LANG']['tl_banner']['banner_url']['0'] = "URL баннера";
$GLOBALS['TL_LANG']['tl_banner']['banner_url']['1'] = "Пожалуйста, введите URL баннера: http://...";
$GLOBALS['TL_LANG']['tl_banner']['banner_jumpTo']['0'] = "Целевая страница баннера";
$GLOBALS['TL_LANG']['tl_banner']['banner_jumpTo']['1'] = "Пожалуйста, выберите целевую страницу. Этот выбор имеет приоритет над ссылкой \"URL баннера\".";
$GLOBALS['TL_LANG']['tl_banner']['banner_target']['0'] = "Внутренняя ссылка";
$GLOBALS['TL_LANG']['tl_banner']['banner_target']['1'] = "Если вы выберете этот вариант, ссылка баннера откроется в том же окне браузера.";
$GLOBALS['TL_LANG']['tl_banner']['banner_image']['0'] = "Изображение баннера";
$GLOBALS['TL_LANG']['tl_banner']['banner_image']['1'] = "Пожалуйста, выберите изображение баннера. (GIF,JPG,PNG,SWF)";
$GLOBALS['TL_LANG']['tl_banner']['banner_image_extern']['0'] = "URL изображения баннера";
$GLOBALS['TL_LANG']['tl_banner']['banner_image_extern']['1'] = "Внешнее изображение баннера URL: http:// ...";
$GLOBALS['TL_LANG']['tl_banner']['banner_imgSize']['0'] = "Ширина и высота изображения";
$GLOBALS['TL_LANG']['tl_banner']['banner_imgSize']['1'] = "Если вы введете только ширину или только высоту изображения (в пикселах), то изображение будет изменено пропорционально. Если вы введете оба значения, то изображение будет обрезано в случае необходимости. Если оставите оба поля пустыми, то изображение будет отображено в оригинальном размере.<br />NOTE: Анимированные GIF при задании размеров будут преобразованы в статические.";
$GLOBALS['TL_LANG']['tl_banner']['banner_comment']['0'] = "Комментарий баннера";
$GLOBALS['TL_LANG']['tl_banner']['banner_comment']['1'] = "Комментарий баннера.";
$GLOBALS['TL_LANG']['tl_banner']['banner_weighting']['0'] = "Вес баннера";
$GLOBALS['TL_LANG']['tl_banner']['banner_weighting']['1'] = "Пожалуйста, выберите приоритет.";
$GLOBALS['TL_LANG']['tl_banner']['banner_published']['0'] = "Опубликовать";
$GLOBALS['TL_LANG']['tl_banner']['banner_published']['1'] = "Если вы не выберете эту опцию, этот баннер не будет показан.";
$GLOBALS['TL_LANG']['tl_banner']['banner_start']['0'] = "Показывать с";
$GLOBALS['TL_LANG']['tl_banner']['banner_start']['1'] = "Если вы введете здесь дату и время, то текущий баннер не будет показан на вебсайте раньше этого момента.";
$GLOBALS['TL_LANG']['tl_banner']['banner_stop']['0'] = "Показывать до";
$GLOBALS['TL_LANG']['tl_banner']['banner_stop']['1'] = "Если вы введете здесь дату и время, то текущий баннер не будет показан на вебсайте позже этого момента.";
$GLOBALS['TL_LANG']['tl_banner']['banner_until']['0'] = "Ограничение числа просмотров и кликов";
$GLOBALS['TL_LANG']['tl_banner']['banner_until']['1'] = "Если вы выберете эту опцию, то сможете определить максимальное число просмотров и/или максимальное число кликов баннера.";
$GLOBALS['TL_LANG']['tl_banner']['banner_views_until']['0'] = "Ограничение числа просмотров";
$GLOBALS['TL_LANG']['tl_banner']['banner_views_until']['1'] = "Если число введено, текущий баннер не будет отображаться после этого количества просмотров.";
$GLOBALS['TL_LANG']['tl_banner']['banner_clicks_until']['0'] = "Ограничение числа нажатий";
$GLOBALS['TL_LANG']['tl_banner']['banner_clicks_until']['1'] = "Если число введено, текущий баннер не будет отображаться после этого количества нажатий.";
$GLOBALS['TL_LANG']['tl_banner']['banner_cat_not_found'] = "Нет выбранной категории в модуле баннеров.";
$GLOBALS['TL_LANG']['tl_banner']['title_legend'] = "Имя и вес";
$GLOBALS['TL_LANG']['tl_banner']['destination_legend'] = "Цель баннера";
$GLOBALS['TL_LANG']['tl_banner']['image_legend'] = "Изображение баннера";
$GLOBALS['TL_LANG']['tl_banner']['comment_legend'] = "Комментарий";
$GLOBALS['TL_LANG']['tl_banner']['publish_legend'] = "Настройки публикации";
$GLOBALS['TL_LANG']['tl_banner']['1'] = "Высокий приоритет";
$GLOBALS['TL_LANG']['tl_banner']['2'] = "Нормальный приоритет";
$GLOBALS['TL_LANG']['tl_banner']['3'] = "Низкий приоритет";
$GLOBALS['TL_LANG']['tl_banner']['tl_be_start'] = "Показывать с";
$GLOBALS['TL_LANG']['tl_banner']['tl_be_stop'] = "Показывать до";
$GLOBALS['TL_LANG']['tl_banner']['tl_be_yes'] = "да";
$GLOBALS['TL_LANG']['tl_banner']['tl_be_no'] = "нет";
$GLOBALS['TL_LANG']['tl_banner']['tl_be_not_defined_start'] = "немедленно";
$GLOBALS['TL_LANG']['tl_banner']['tl_be_not_defined_stop'] = "всегда";
$GLOBALS['TL_LANG']['tl_banner']['tl_be_max_views'] = "макс. просмотров";
$GLOBALS['TL_LANG']['tl_banner']['tl_be_max_clicks'] = "макс. нажатий";
$GLOBALS['TL_LANG']['tl_banner']['tl_be_not_defined_max'] = "неограниченно";
$GLOBALS['TL_LANG']['tl_banner']['tl_be_read_error'] = "Не найден файл баннера или ошибка чтения!";
$GLOBALS['TL_LANG']['tl_banner']['source_intern'] = "внутренний";
$GLOBALS['TL_LANG']['tl_banner']['source_extern'] = "внешний";
$GLOBALS['TL_LANG']['tl_banner']['new']['0'] = "Новый баннер";
$GLOBALS['TL_LANG']['tl_banner']['new']['1'] = "Добавить новый баннер";
$GLOBALS['TL_LANG']['tl_banner']['edit']['0'] = "Редактировать баннер";
$GLOBALS['TL_LANG']['tl_banner']['edit']['1'] = "Редактировать баннер ID %s";
$GLOBALS['TL_LANG']['tl_banner']['copy']['0'] = "Копировать баннер";
$GLOBALS['TL_LANG']['tl_banner']['copy']['1'] = "Копировать баннер ID %s";
$GLOBALS['TL_LANG']['tl_banner']['delete']['0'] = "Удалить баннер";
$GLOBALS['TL_LANG']['tl_banner']['delete']['1'] = "Удалить баннер ID %s";
$GLOBALS['TL_LANG']['tl_banner']['show']['0'] = "Детали баннера";
$GLOBALS['TL_LANG']['tl_banner']['show']['1'] = "Показать детали баннера ID %s";
$GLOBALS['TL_LANG']['tl_banner']['toggle']['0'] = "Переключение видимости";
$GLOBALS['TL_LANG']['tl_banner']['toggle']['1'] = "Переключения видимости баннера ID %s";
$GLOBALS['TL_LANG']['tl_banner_type']['default'] = "Пожалуйста, выберите";
$GLOBALS['TL_LANG']['tl_banner_type']['banner_image'] = "Внутреннее изображение баннера";
$GLOBALS['TL_LANG']['tl_banner_type']['banner_image_extern'] = "Внешнее изображение баннера";
$GLOBALS['TL_LANG']['tl_banner_type']['banner_text'] = "Текст баннера";
 
?>
