<?php
/**
 * TL_ROOT/system/modules/banner/languages/ru/tl_banner_category.php 
 * 
 * TYPOlight extension: banner 1.10.0 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; 2007..2010 Glen Langer 
 * License   : GNU GPL V2 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Dmitry Kuznetsov (kuzmich), http://on.freedom-vrn.ru 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_banner_category']['title']['0'] = "Категория";
$GLOBALS['TL_LANG']['tl_banner_category']['title']['1'] = "Пожалуйста, введите название категории.";
$GLOBALS['TL_LANG']['tl_banner_category']['tstamp']['0'] = "Дата редакции";
$GLOBALS['TL_LANG']['tl_banner_category']['tstamp']['1'] = "Дата и время последней редакции";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default']['0'] = "Стандартное изображение баннера";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default']['1'] = "Этот баннер будет показан, если не найдены активные баннеры.<br />Выбор опции имеет приоритет над опцией \"Скрыть модуль если пусто\".";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default_name']['0'] = "Имя баннера";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default_name']['1'] = "Имя для тега заголовка.";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default_image']['0'] = "Изображение баннера по умолчанию";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default_image']['1'] = "Пожалуйста, выберите баннер. (GIF, JPG, PNG, SWF)";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default_url']['0'] = "Целевой URL баннера";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default_url']['1'] = "Пожалуйста, введите целевой URL баннера: http://...";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default_target']['0'] = "Внутренняя ссылка";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default_target']['1'] = "Если вы выберете этот вариант, ссылка баннера откроется в том же окне браузера.";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_protected']['0'] = "Защита категории";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_protected']['1'] = "Показывать банер этой категории только определенным участникам группы.";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_groups']['0'] = "Разрешено участникам групп";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_groups']['1'] = "Здесь вы сможете выбрать, какие группы будут иметь возможность видеть баннеры этой категории.";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_numbers']['0'] = "Показать все баннеры";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_numbers']['1'] = "Если вы выберете эту опцию, все активные баннеры будут показаны в интерфейсе.";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_random']['0'] = "Случайный порядок";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_random']['1'] = "Если вы выберете эту опцию, баннеры будут показаны в случайном порядке.";
$GLOBALS['TL_LANG']['tl_banner_category']['title_legend'] = "Категория и шаблон баннера";
$GLOBALS['TL_LANG']['tl_banner_category']['default_legend'] = "Детали баннера по умолчанию";
$GLOBALS['TL_LANG']['tl_banner_category']['protected_legend'] = "Защита доступа";
$GLOBALS['TL_LANG']['tl_banner_category']['number_legend'] = "Количество баннеров";
$GLOBALS['TL_LANG']['tl_banner_category']['deleteConfirm'] = "Удаление категории также удалит все свои баннеры! Вы действительно хотите удалить категорию ID %s?";
$GLOBALS['TL_LANG']['tl_banner_category']['new']['0'] = "Новая категория";
$GLOBALS['TL_LANG']['tl_banner_category']['new']['1'] = "Создание новой категории";
$GLOBALS['TL_LANG']['tl_banner_category']['edit']['0'] = "Редактировать категорию";
$GLOBALS['TL_LANG']['tl_banner_category']['edit']['1'] = "Редактировать категорию ID %s";
$GLOBALS['TL_LANG']['tl_banner_category']['copy']['0'] = "Копировать категорию";
$GLOBALS['TL_LANG']['tl_banner_category']['copy']['1'] = "Копировать категорию ID %s";
$GLOBALS['TL_LANG']['tl_banner_category']['delete']['0'] = "Удалить категорию";
$GLOBALS['TL_LANG']['tl_banner_category']['delete']['1'] = "Удалить категорию ID %s";
$GLOBALS['TL_LANG']['tl_banner_category']['show']['0'] = "Детали категории";
$GLOBALS['TL_LANG']['tl_banner_category']['show']['1'] = "Показать детали категории ID %s";
$GLOBALS['TL_LANG']['tl_banner_category']['stat']['0'] = "Статистика категории";
$GLOBALS['TL_LANG']['tl_banner_category']['stat']['1'] = "Показать статистику категории ID %s";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_protected_catagory'] = "Защищаемая категория";
 
?>