<?php
/**
 * TL_ROOT/system/modules/banner/languages/ru/tl_module.php 
 * 
 * TYPOlight extension: banner 1.10.0 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; 2007..2010 Glen Langer 
 * License   : GNU GPL V2 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Dmitry Kuznetsov (kuzmich), http://on.freedom-vrn.ru 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['banner_hideempty']['0'] = "Скрыть модуль если пусто";
$GLOBALS['TL_LANG']['tl_module']['banner_hideempty']['1'] = "Скрывать модуль во внешнем интерфейсе, если активные баннеры не найдены.";
$GLOBALS['TL_LANG']['tl_module']['banner_categories']['0'] = "Категории баннеров";
$GLOBALS['TL_LANG']['tl_module']['banner_categories']['1'] = "Пожалуйста, выберите категорию баннеров, которую хотите включить.";
$GLOBALS['TL_LANG']['tl_module']['banner_template']['0'] = "Шаблон баннера";
$GLOBALS['TL_LANG']['tl_module']['banner_template']['1'] = "Пожалуйста, выберите шаблон баннера. Файлы шаблонов баннера начинаются с <em>mod_banner_list_</em>.";
$GLOBALS['TL_LANG']['tl_module']['banner_useragent']['0'] = "Не считая этого HTTP_USER_AGENT идентификатора";
$GLOBALS['TL_LANG']['tl_module']['banner_useragent']['1'] = "Здесь вы можете указать идентификатор, который не будет посчитан. Этот HTTP_USER_AGENT идентификатор браузера должн быть изменен. <br /> См. Wiki.";
 
?>