<?php
/**
 * TL_ROOT/system/modules/banner/languages/pl/default.php 
 * 
 * TYPOlight extension: banner 1.6.5 stable 
 * Polnisch translation file 
 * 
 * Copyright : &copy; 2007..2008 Glen Langer 
 * License   : GNU GPL V2 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Marcin Lachowski (qrczak), http://www.typolight.pl 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['id'] = "ID";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['picture'] = "Baner";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['name'] = "Nazwa";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['URL'] = "Docelowy URL";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['views'] = "Odsłon";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['clicks'] = "Kliknięć";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['NoURL'] = "Bez URL";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['Prio'] = "Priorytet";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['active'] = "Aktywny";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['pub_yes'] = "tak";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['pub_no'] = "nie";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['max_yes'] = "(Maksymum)";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['modname'] = "Moduł Baner";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['export'] = "Eksport";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['export_button_title'] = "Przycisk otwiera nowe okno.";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['export_headline'] = "Kategoria,ID,Nazwa,URL,Obrazek,Priorytet,Pokaż od,Pokaż do,Opublikowany,Wyświetleń,Kliknięć";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['zero_text'] = "Statystyki banera zostaną zresetowane do zera.";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['zero_confirm'] = "Czy naprawdę chcesz zresetować licznik statystyk banera (wyświetlenia i kliknięcia)?";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['kat'] = "Kategoria";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['read_error'] = "Nie znaleziono pliku banera lub błąd odczytu!";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['select'] = "Zaznacz";
 
?>
