<?php
/**
 * TL_ROOT/system/modules/banner/languages/pl/modules.php 
 * 
 * TYPOlight extension: banner 1.6.5 stable 
 * Polish translation file 
 * 
 * Copyright : &copy; 2007..2009 Glen Langer 
 * License   : GNU GPL V2 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Marcin Lachowski (qrczak), http://www.typolight.pl 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['banner']['0'] = "Baner";
$GLOBALS['TL_LANG']['MOD']['banner']['1'] = "Moduł do obsługi banerów reklamowych.";
$GLOBALS['TL_LANG']['MOD']['bannerstat']['0'] = "Statystyki banera";
$GLOBALS['TL_LANG']['MOD']['bannerstat']['1'] = "Statystyki banerów";
$GLOBALS['TL_LANG']['FMD']['banner']['0'] = "Baner";
$GLOBALS['TL_LANG']['FMD']['banner']['1'] = "Pokaż baner";
 
?>
