<?php
/**
 * TL_ROOT/system/modules/banner/languages/pl/tl_banner_category.php 
 * 
 * TYPOlight extension: banner 1.6.5 stable 
 * Polnisch translation file 
 * 
 * Copyright : &copy; 2007..2008 Glen Langer 
 * License   : GNU GPL V2 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Marcin Lachowski (qrczak), http://www.typolight.pl 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_banner_category']['title']['0'] = "Kategoria";
$GLOBALS['TL_LANG']['tl_banner_category']['title']['1'] = "Wpisz nazwę kategorii";
$GLOBALS['TL_LANG']['tl_banner_category']['tstamp']['0'] = "Data rewizji";
$GLOBALS['TL_LANG']['tl_banner_category']['tstamp']['1'] = "Data i czas ostatniej rewizji";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default']['0'] = "Domyślny obrazek banera";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default']['1'] = "Domyślny obrazek banera będzie wyświetlany, kiedy moduł nie znajdzie aktywnych banerów.<br />Te ustawienie zastępuje opcję \"Ukryj kiedy pusty\".";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default_name']['0'] = "Nazwa banera";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default_name']['1'] = "Nazwa banera jest równiez wykozystywana jako tag title w kodzie HTML.";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default_image']['0'] = "Domyślny obrazek banera";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default_image']['1'] = "Wybierz obrazek banera. (GIF,JPG,PNG,SWF)";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default_target']['0'] = "Wewnętrzny odnośnik";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default_target']['1'] = "Jeśli zaznaczysz tę opcję, docelowy URL banera otworzy się w tym samym oknie przeglądarki.";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_protected']['0'] = "Kategoria chroniona";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_protected']['1'] = "Pokaż banery z tej kategorii tylko dla konkretnej grupy członków.";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_groups']['0'] = "Dopuść grupy członków";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_groups']['1'] = "Tu możesz wybrać, które grupy członków będą mogły oglądać banery z tej kategorii.";
$GLOBALS['TL_LANG']['tl_banner_category']['deleteConfirm'] = "Usunięcie kategorii spowoduje usunięcie również banerów w niej zawartych! Czy na pewno chcesz usunąć kategorię ID %s?";
$GLOBALS['TL_LANG']['tl_banner_category']['new']['0'] = "Nowa kategoria";
$GLOBALS['TL_LANG']['tl_banner_category']['new']['1'] = "Utwórz nową kategorię";
$GLOBALS['TL_LANG']['tl_banner_category']['edit']['0'] = "Edytuj kategorię";
$GLOBALS['TL_LANG']['tl_banner_category']['edit']['1'] = "Edytuj kategorię ID %s";
$GLOBALS['TL_LANG']['tl_banner_category']['copy']['0'] = "Kopiuj kategorię";
$GLOBALS['TL_LANG']['tl_banner_category']['copy']['1'] = "Kopiuj kategorię ID %s";
$GLOBALS['TL_LANG']['tl_banner_category']['delete']['0'] = "Usuń kategorię";
$GLOBALS['TL_LANG']['tl_banner_category']['delete']['1'] = "Usuń kategorię ID %s";
$GLOBALS['TL_LANG']['tl_banner_category']['show']['0'] = "Szczegóły kategorii";
$GLOBALS['TL_LANG']['tl_banner_category']['show']['1'] = "Pokaż szczegóły kategorii ID %s";
$GLOBALS['TL_LANG']['tl_banner_category']['stat']['0'] = "Statystyki kategorii";
$GLOBALS['TL_LANG']['tl_banner_category']['stat']['1'] = "Pokaż statystyki kategorii ID %s";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_protected_catagory'] = "Kategoria chroniona";
 
?>