<?php
/**
 * TL_ROOT/system/modules/banner/languages/pl/tl_module.php 
 * 
 * TYPOlight extension: banner 1.6.5 stable 
 * Polnisch translation file 
 * 
 * Copyright : &copy; 2007..2008 Glen Langer 
 * License   : GNU GPL V2 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Marcin Lachowski (qrczak), http://www.typolight.pl 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['banner_hideempty']['0'] = "Ukryj kiedy pusty";
$GLOBALS['TL_LANG']['tl_module']['banner_hideempty']['1'] = "Moduł nie wstawi na stronę żadnego kodu jeśli nie znajdzie żadnych aktywnych banerów.";
$GLOBALS['TL_LANG']['tl_module']['banner_categories']['0'] = "Kategorie banerów";
$GLOBALS['TL_LANG']['tl_module']['banner_categories']['1'] = "Zaznacz kategorie banerów, które chcesz załączyć.";
$GLOBALS['TL_LANG']['tl_module']['banner_template']['0'] = "Szablon banera";
$GLOBALS['TL_LANG']['tl_module']['banner_template']['1'] = "Wybierz szablon banera. Możesz dodać dowolny szablon do folderu <em>templates</em>. Pliki szablonów zaczynają się od <em>mod_banner_list_</em> i muszą mieć rozszerzenie .tpl.";

 
?>