<?php
/**
 * TL_ROOT/system/modules/banner/languages/fa/default.php 
 * 
 * Contao extension: banner 2.0.0 rc1 
 * Persian translation file 
 * 
 * Copyright : &copy; 2007..2010 Glen Langer 
 * License   : GNU GPL V2 
 * Author    : Glen Langer (BugBuster), http://www.contao.glen-langer.de 
 * Translator: Hamid Abbaszadeh (respinar), http://www.respinar.com/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['id'] = "شناسه";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['picture'] = "بنر";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['name'] = "نام";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['URL'] = "URL مقصد";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['views'] = "بازدیدها";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['clicks'] = "کلیک ها";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['NoURL'] = "بدون URL";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['Prio'] = "اولویت";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['active'] = "فعال";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['pub_yes'] = "بلی";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['pub_no'] = "خیر";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['max_yes'] = "(بیشینه)";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['modname'] = "ماژول بنر";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['export'] = "خروجی";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['export_headline'] = "شاخه، شناسه، نام، URL، تصویر،اولویت، مشاهده از، مشاهده تا، منتشر شده، مشاهده ها، کلیک ها";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['zero_text'] = "شمارنده آمار بنر به صفر تنظیم خواهد شد.";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['kat'] = "شاخه";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['allkat'] = "همه شاخه ها";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['read_error'] = "فایل بنر یافت نشد و یا خطای خواندن رخ داد!";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['select'] = "انتخاب کنید";
 
?>
