<?php
/**
 * TL_ROOT/system/modules/banner/languages/fa/modules.php 
 * 
 * Contao extension: banner 2.0.0 rc1 
 * Persian translation file 
 * 
 * Copyright : &copy; 2007..2010 Glen Langer 
 * License   : GNU GPL V2 
 * Author    : Glen Langer (BugBuster), http://www.contao.glen-langer.de 
 * Translator: Hamid Abbaszadeh (respinar), http://www.respinar.com/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['banner']['0'] = "بنر";
$GLOBALS['TL_LANG']['MOD']['banner']['1'] = "ماژول تبلیغاتی بنر کوچک";
$GLOBALS['TL_LANG']['MOD']['bannerstat']['0'] = "آمار بنر";
$GLOBALS['TL_LANG']['MOD']['bannerstat']['1'] = "آمار از ماژول بنر";
$GLOBALS['TL_LANG']['FMD']['banner']['0'] = "بنر";
$GLOBALS['TL_LANG']['FMD']['banner']['1'] = "نمایش یک بنر";
 
?>
