<?php
/**
 * TL_ROOT/system/modules/banner/languages/fa/tl_banner_category.php 
 * 
 * Contao extension: banner 2.0.0 rc1 
 * Persian translation file 
 * 
 * Copyright : &copy; 2007..2010 Glen Langer 
 * License   : GNU GPL V2 
 * Author    : Glen Langer (BugBuster), http://www.contao.glen-langer.de 
 * Translator: Hamid Abbaszadeh (respinar), http://www.respinar.com/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_banner_category']['title']['0'] = "شاخه";
$GLOBALS['TL_LANG']['tl_banner_category']['title']['1'] = "نام شاخه را وارد کنید";
$GLOBALS['TL_LANG']['tl_banner_category']['tstamp']['0'] = "تاریخ بازنگری";
$GLOBALS['TL_LANG']['tl_banner_category']['tstamp']['1'] = "تاریخ و ساعت آخرین بازنگری";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default']['0'] = "تصویر بنر پیش فرض";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default_name']['0'] = "نام بنر";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default_name']['1'] = "نام برای برچشب عنوان نیز می باشد.";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default_image']['0'] = "تصویر پیشفرض بنر";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default_image']['1'] = "بنر را انتخاب کنید . (GIF,JPG,PNG,SWF)";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default_url']['0'] = "URL مقصد بنر";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default_url']['1'] = "URL مقصد بنر را وارد کنید: http://...";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_default_target']['0'] = "پیوند داخلی";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_protected']['0'] = "حفاظت شاخه";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_groups']['0'] = "گروه های اعضاء مجاز";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_numbers']['0'] = "نمایش همه بنر ها";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_random']['0'] = "ترتیب تصافی";
$GLOBALS['TL_LANG']['tl_banner_category']['title_legend'] = "شاخه و قالب بنر";
$GLOBALS['TL_LANG']['tl_banner_category']['default_legend'] = "جزئیات بنر پیش فرض";
$GLOBALS['TL_LANG']['tl_banner_category']['protected_legend'] = "محافظت دسترسی";
$GLOBALS['TL_LANG']['tl_banner_category']['number_legend'] = "تعداد بنرها";
$GLOBALS['TL_LANG']['tl_banner_category']['new']['0'] = "شاخه جدید";
$GLOBALS['TL_LANG']['tl_banner_category']['new']['1'] = "ایجاد شاخه جدید";
$GLOBALS['TL_LANG']['tl_banner_category']['edit']['0'] = "ویرایش شاخه";
$GLOBALS['TL_LANG']['tl_banner_category']['edit']['1'] = "ویرایش شاخه شناسه %s";
$GLOBALS['TL_LANG']['tl_banner_category']['copy']['0'] = "کپی شاخه";
$GLOBALS['TL_LANG']['tl_banner_category']['copy']['1'] = "کپی شاخه شناسه %s";
$GLOBALS['TL_LANG']['tl_banner_category']['delete']['0'] = "حذف شاخه";
$GLOBALS['TL_LANG']['tl_banner_category']['delete']['1'] = "حذف شاخه شناسه %s";
$GLOBALS['TL_LANG']['tl_banner_category']['show']['0'] = "جزئیات شاخه";
$GLOBALS['TL_LANG']['tl_banner_category']['show']['1'] = "نمایش جزئیات شاخه شناسه %s";
$GLOBALS['TL_LANG']['tl_banner_category']['stat']['0'] = "آمار شاخه";
$GLOBALS['TL_LANG']['tl_banner_category']['stat']['1'] = "نمایش آمار شاخه شناسه %s";
$GLOBALS['TL_LANG']['tl_banner_category']['banner_protected_catagory'] = "شاخه حفاظت شده";
 
?>
