<?php
/**
 * TL_ROOT/system/modules/banner/languages/fa/tl_module.php 
 * 
 * Contao extension: banner 2.0.0 rc1 
 * Persian translation file 
 * 
 * Copyright : &copy; 2007..2010 Glen Langer 
 * License   : GNU GPL V2 
 * Author    : Glen Langer (BugBuster), http://www.contao.glen-langer.de 
 * Translator: Hamid Abbaszadeh (respinar), http://www.respinar.com/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['banner_hideempty']['0'] = "پنهان کردن وقتی خالی است";
$GLOBALS['TL_LANG']['tl_module']['banner_categories']['0'] = "شاخه های بنر";
$GLOBALS['TL_LANG']['tl_module']['banner_categories']['1'] = "شاخه بنر را انتخاب کنید";
$GLOBALS['TL_LANG']['tl_module']['banner_template']['0'] = "قالب بنر";
$GLOBALS['TL_LANG']['tl_module']['banner_template']['1'] = "Please choose the Banner-Template. Banner template files start with <em>mod_banner_list_</em>.";
$GLOBALS['TL_LANG']['tl_module']['banner_useragent']['0'] = "No counting for this HTTP_USER_AGENT partial identifier";
$GLOBALS['TL_LANG']['tl_module']['banner_useragent']['1'] = "Here you can specify a partial identifier, it will be no counting. These HTTP_USER_AGENT partial identifier of the browser must be changed.<br />See Wiki.";
 
?>
