<?php
/**
 * TL_ROOT/system/modules/banner/languages/fr/default.php 
 * 
 * TYPOlight extension: banner 1.10.1 stable 
 * French translation file 
 * 
 * Copyright : &copy; 2007..2010 Glen Langer 
 * License   : GNU GPL V2 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Jérôme DENIS (irongomme), http://www.sweb-developpement.com 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['id'] = "ID";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['picture'] = "Bannière";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['name'] = "Nom";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['URL'] = "URL cible";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['views'] = "Vues";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['clicks'] = "Clics";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['NoURL'] = "Sans URL";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['Prio'] = "Priorité";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['active'] = "Active";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['pub_yes'] = "oui";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['pub_no'] = "non";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['max_yes'] = "(Maximum)";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['modname'] = "Module bannière";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['export'] = "Exporter";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['export_button_title'] = "Le bouton ouvre une nouvelle fenêtre";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['export_headline'] = "Catégorie,ID,Nom,URL,Image,Priorité,Publié depuis,Publié jusqu'au,Publié,Vues,Clics";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['zero_text'] = "Le compteur des statistiques de la bannière sera réinitialisé à zéro.";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['zero_confirm'] = "Souhaitez-vous vraiment réinitialiser le compteur des statistiques de la bannière (vues et clics)?";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['kat'] = "Catégorie";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['allkat'] = "Toutes les catégorie";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['read_error'] = "Fichier bannière non trouvé ou erreur de lecture!";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['select'] = "Veuillez sélectionner";
 
?>
