<?php
/**
 * TL_ROOT/system/modules/banner/languages/fr/modules.php 
 * 
 * TYPOlight extension: banner 1.10.1 stable 
 * French translation file 
 * 
 * Copyright : &copy; 2007..2010 Glen Langer 
 * License   : GNU GPL V2 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Jérôme DENIS (irongomme), http://www.sweb-developpement.com 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['banner']['0'] = "Bannière";
$GLOBALS['TL_LANG']['MOD']['banner']['1'] = "Un petit module de bannière publicitaire.";
$GLOBALS['TL_LANG']['MOD']['bannerstat']['0'] = "Statistiques bannière";
$GLOBALS['TL_LANG']['MOD']['bannerstat']['1'] = "Statistiques bannière en provenance du module bannière.";
$GLOBALS['TL_LANG']['FMD']['banner']['0'] = "Bannière";
$GLOBALS['TL_LANG']['FMD']['banner']['1'] = "Afficher une bannière";
 
?>
