<?php
/**
 * TL_ROOT/system/modules/banner/languages/fr/tl_module.php 
 * 
 * TYPOlight extension: banner 1.10.1 stable 
 * French translation file 
 * 
 * Copyright : &copy; 2007..2010 Glen Langer 
 * License   : GNU GPL V2 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Jérôme DENIS (irongomme), http://www.sweb-developpement.com 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['banner_hideempty']['0'] = "Cacher quand vide";
$GLOBALS['TL_LANG']['tl_module']['banner_hideempty']['1'] = "Cacher ce module (partie publique) quand aucune bannière active n'est trouvée";
$GLOBALS['TL_LANG']['tl_module']['banner_categories']['0'] = "Catégories bannières";
$GLOBALS['TL_LANG']['tl_module']['banner_categories']['1'] = "Veuillez sélectionner les catégorie de bannière que vous souhaitez inclure.";
$GLOBALS['TL_LANG']['tl_module']['banner_template']['0'] = "Modèle Bannière";
$GLOBALS['TL_LANG']['tl_module']['banner_template']['1'] = "Veuillez choisir le modèle de la bannière. Les fichiers des modèles de bannière commencent par <em>mod_banner_list_</em>.";
$GLOBALS['TL_LANG']['tl_module']['banner_useragent']['0'] = "Aucun résultat pour cet identificateur HTTP_USER_AGENT";
$GLOBALS['TL_LANG']['tl_module']['banner_useragent']['1'] = "Ici vous pouvez préciser un identificateur partiel, qui ne sera pas compté. Cet identificateur partiel du navigateur HTTP_USER_AGENT doit être modifié.<br />Lisez le Wiki.";
 
?>
